inherits = "nord"

#"ui.background" = { modifiers = [ "hidden" ] }

# The rest of this is unfinished; nord is just a good "go to".
# This may or may not be finished in the future;
# we're missing syntax highlighting-related colors.

#"ui.statusline" = { fg = "white", bg = "black" }
#"ui.statusline.insert" = { fg = "cyan", bg = "black" }
#"ui.statusline.normal" = { fg = "green", bg = "black" }
#"ui.statusline.select" = { fg = "red", bg = "black" }
#"ui.statusline.separator" = { fg = "light-white", bg = "light-white", modifiers = ["bold"] }
#
#"ui.selection" = { modifiers = ["hidden"] }
#
#"ui.linenr" = "light-black"
#"ui.linenr.selected" = "light-yellow"
#
#"ui.popup" = { fg = "blue", bg = "black" }
#
#"ui.menu" = { fg = "light-blue", bg = "black" }
#"ui.menu.selected" = { modifiers = ["reversed"] }
#
#
#"diff.plus" = { fg = "green" }
#"diff.delta" = { fg = "yellow" }
#"diff.minus" = { fg = "red" }
#
#"warning" = { fg = "light-yellow" }
#"error" = { fg = "light-red" }
#"info" = { fg = "light-blue" }
#"hint" = { fg = "light-magenta" }
#
#[palette]
#black   = "#2e2e2e"
#red     = "#f7748d"
#green   = "#76eda3"
#yellow  = "#f7bf65"
#blue    = "#4da4f0"
#magenta = "#e88be0"
#cyan    = "#1ddbc9"
#white   = "#e9e9e9"
#
#light-black   = "#5c5c5c"
#light-red     = "#ff9caa"
#light-green   = "#a4edac"
#light-yellow  = "#f7e2a1"
#light-blue    = "#b7c8ff"
#light-magenta = "#edbbe9"
#light-cyan    = "#81f5e1"
#light-white   = "#f5f5f5"
